# test_client.py

import socketio
import time

# Create a standard SocketIO client
sio = socketio.Client()

# --- CONFIGURATION ---
# In a real app, this token is generated by Firebase Auth on your phone
MOCK_TOKEN = "test_user_12345" 
TEST_URL = "https://stackoverflow.com/users/login"

@sio.event
def connect():
    print("✅ Connected to CyberGuard AI Backend!")
    
    # We now send the URL AND the Token as required by our new backend logic
    payload = {
        'url': TEST_URL,
        'token': MOCK_TOKEN
    }
    
    print(f"🚀 [Mobile Mock] Sending authenticated request for: {TEST_URL}")
    sio.emit('scan_request', payload)

@sio.on('scan_update')
def on_update(data):
    # Simulates the progress bar moving on the React Native UI
    progress = int(data.get('progress', 0) * 100)
    print(f"⏳ [UI Progress {progress}%]: {data['message']}")

@sio.on('scan_result')
def on_result(data):
    print("\n" + "⭐" * 40)
    print("        SCAN COMPLETED SUCCESSFULLY")
    print("⭐" * 40)
    print(f"USER ID    : {data.get('uid', 'Verified User')}") # Ensure uid is returned
    print(f"PREDICTION : {data['prediction'].upper()}")
    print(f"CONFIDENCE : {data['confidence']}%")
    print(f"RESOLVED IN: Tier {data['tier_resolved']}")
    print(f"LATENCY    : {data['latency_ms']}ms")
    print("⭐" * 40 + "\n")
    sio.disconnect()

@sio.on('scan_error')
def on_error(data):
    print(f"\n❌ [SERVER ERROR]: {data['error']}")
    if 'details' in data:
        print(f"   Details: {data['details']}")
    sio.disconnect()

@sio.event
def disconnect():
    print("🔴 Disconnected from server.")

if __name__ == '__main__':
    try:
        # Change this IP if your server is running on a different machine
        sio.connect('http://127.0.0.1:5000')
        sio.wait()
    except Exception as e:
        print(f"FATAL: Could not connect to backend: {e}")