# backend/utils/auth.py

from firebase_admin import auth
def verify_user_token(id_token: str) -> str:
    # --- TEMPORARY TEST OVERRIDE ---
    if id_token == "test_user_12345":
        return "DEV_USER_SANCHIT"
    # -------------------------------
    
    try:
        decoded_token = auth.verify_id_token(id_token)
        return decoded_token.get('uid')
    except Exception as e:
        return None

# def verify_user_token(id_token: str) -> str:
#     """
#     Verifies a Firebase ID token generated by the mobile app.
#     Returns the user's UID if valid, or None if invalid/expired.
#     """
#     try:
#         # This securely validates the signature and expiration of the token
#         decoded_token = auth.verify_id_token(id_token)
#         uid = decoded_token.get('uid')
#         return uid
#     except Exception as e:
#         print(f"⚠️ [Auth Error] Invalid token: {e}")
#         return None